-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 16:39:37 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fiscale_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiscale_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiscale_db` DEFAULT CHARACTER SET utf8 ;
USE `fiscale_db` ;

-- -----------------------------------------------------
-- Table `fiscale_db`.`Ville`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Ville` (
  `idville` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `code postal` VARCHAR(10) NULL,
  PRIMARY KEY (`idville`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Adresse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Adresse` (
  `idAdresse` INT NOT NULL AUTO_INCREMENT,
  `rue` VARCHAR(100) NULL,
  `numero` VARCHAR(10) NULL,
  `complement` VARCHAR(100) NULL,
  `Ville_idville` INT NOT NULL,
  PRIMARY KEY (`idAdresse`),
  INDEX `fk_Adresse_Ville1_idx` (`Ville_idville` ASC) VISIBLE,
  CONSTRAINT `fk_Adresse_Ville1`
    FOREIGN KEY (`Ville_idville`)
    REFERENCES `fiscale_db`.`Ville` (`idville`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Client` (
  `idclient` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NULL,
  `prenom` VARCHAR(100) NULL,
  `email` VARCHAR(150) NULL,
  `telephone` VARCHAR(20) NULL,
  `mot de passe` VARCHAR(50) NULL,
  `IBAN` VARCHAR(50) NULL,
  `Adresse_idAdresse` INT NOT NULL,
  PRIMARY KEY (`idclient`, `Adresse_idAdresse`),
  INDEX `fk_Client_Adresse_idx` (`Adresse_idAdresse` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Adresse`
    FOREIGN KEY (`Adresse_idAdresse`)
    REFERENCES `fiscale_db`.`Adresse` (`idAdresse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Independant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Independant` (
  `numero_entreprise` INT NOT NULL AUTO_INCREMENT,
  `nom_entreprise` VARCHAR(50) NULL,
  `date_debut_entreprise` VARCHAR(45) NULL,
  `Client_idclient` INT NOT NULL,
  PRIMARY KEY (`numero_entreprise`),
  INDEX `fk_Independant_Client1_idx` (`Client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_Independant_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Particulier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Particulier` (
  `registre_national` INT NOT NULL AUTO_INCREMENT,
  `Client_idclient` INT NOT NULL,
  PRIMARY KEY (`registre_national`),
  INDEX `fk_Particulier_Client1_idx` (`Client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_Particulier_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Type_impot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Type_impot` (
  `idType_impot` INT NOT NULL AUTO_INCREMENT,
  `denomination` VARCHAR(50) NULL,
  PRIMARY KEY (`idType_impot`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Declaration_fiscale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Declaration_fiscale` (
  `idDeclaration_fiscale` INT NOT NULL AUTO_INCREMENT,
  `annee` INT(10) NULL,
  `lien` VARCHAR(50) NULL,
  `statut` VARCHAR(45) NULL,
  `Client_idclient` INT NOT NULL,
  `Type_impot_idType_impot` INT NOT NULL,
  PRIMARY KEY (`idDeclaration_fiscale`),
  INDEX `fk_Declaration_fiscale_Client1_idx` (`Client_idclient` ASC) VISIBLE,
  INDEX `fk_Declaration_fiscale_Type_impot1_idx` (`Type_impot_idType_impot` ASC) VISIBLE,
  CONSTRAINT `fk_Declaration_fiscale_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Declaration_fiscale_Type_impot1`
    FOREIGN KEY (`Type_impot_idType_impot`)
    REFERENCES `fiscale_db`.`Type_impot` (`idType_impot`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Poste` (
  `idPoste` INT NOT NULL AUTO_INCREMENT,
  `poste` VARCHAR(45) NULL,
  PRIMARY KEY (`idPoste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Membre_cabinet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Membre_cabinet` (
  `idMembre` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(45) NULL,
  `mot_de_passe` VARCHAR(45) NULL,
  `Poste_idPoste` INT NOT NULL,
  PRIMARY KEY (`idMembre`),
  INDEX `fk_Membre_cabinet_Poste1_idx` (`Poste_idPoste` ASC) VISIBLE,
  CONSTRAINT `fk_Membre_cabinet_Poste1`
    FOREIGN KEY (`Poste_idPoste`)
    REFERENCES `fiscale_db`.`Poste` (`idPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Type_depense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Type_depense` (
  `codeType` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`codeType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Type_revenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Type_revenu` (
  `code_Type_revenu` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`code_Type_revenu`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Revenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Revenu` (
  `idRevenu` INT NOT NULL AUTO_INCREMENT,
  `montant` INT(100) NULL,
  `annee_de_perception` INT(10) NULL,
  `Client_idclient` INT NOT NULL,
  `Type_revenu_code_Type_revenu` INT NOT NULL,
  PRIMARY KEY (`idRevenu`),
  INDEX `fk_Revenu_Client1_idx` (`Client_idclient` ASC) VISIBLE,
  INDEX `fk_Revenu_Type_revenu1_idx` (`Type_revenu_code_Type_revenu` ASC) VISIBLE,
  CONSTRAINT `fk_Revenu_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revenu_Type_revenu1`
    FOREIGN KEY (`Type_revenu_code_Type_revenu`)
    REFERENCES `fiscale_db`.`Type_revenu` (`code_Type_revenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Document_revenu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Document_revenu` (
  `idDocument_revenu` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `lien` VARCHAR(45) NULL,
  `Revenu_idRevenu` INT NOT NULL,
  PRIMARY KEY (`idDocument_revenu`),
  INDEX `fk_Document_revenu_Revenu1_idx` (`Revenu_idRevenu` ASC) VISIBLE,
  CONSTRAINT `fk_Document_revenu_Revenu1`
    FOREIGN KEY (`Revenu_idRevenu`)
    REFERENCES `fiscale_db`.`Revenu` (`idRevenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Membre_cabinet_has_Declaration_fiscale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Membre_cabinet_has_Declaration_fiscale` (
  `Membre_cabinet_idMembre` INT NOT NULL,
  `Declaration_fiscale_idDeclaration_fiscale` INT NOT NULL,
  PRIMARY KEY (`Membre_cabinet_idMembre`, `Declaration_fiscale_idDeclaration_fiscale`),
  INDEX `fk_Membre_cabinet_has_Declaration_fiscale_Declaration_fisca_idx` (`Declaration_fiscale_idDeclaration_fiscale` ASC) VISIBLE,
  INDEX `fk_Membre_cabinet_has_Declaration_fiscale_Membre_cabinet1_idx` (`Membre_cabinet_idMembre` ASC) VISIBLE,
  CONSTRAINT `fk_Membre_cabinet_has_Declaration_fiscale_Membre_cabinet1`
    FOREIGN KEY (`Membre_cabinet_idMembre`)
    REFERENCES `fiscale_db`.`Membre_cabinet` (`idMembre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Membre_cabinet_has_Declaration_fiscale_Declaration_fiscale1`
    FOREIGN KEY (`Declaration_fiscale_idDeclaration_fiscale`)
    REFERENCES `fiscale_db`.`Declaration_fiscale` (`idDeclaration_fiscale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Depense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Depense` (
  `idDepense` INT NOT NULL AUTO_INCREMENT,
  `montant` INT(100) NULL,
  `annee_depense` INT(10) NULL,
  `Client_idclient` INT NOT NULL,
  `Type_depense_codeType` INT NOT NULL,
  PRIMARY KEY (`idDepense`),
  INDEX `fk_Depense_Client1_idx` (`Client_idclient` ASC, `Client_Adresse_idAdresse` ASC) VISIBLE,
  INDEX `fk_Depense_Type_depense1_idx` (`Type_depense_codeType` ASC) VISIBLE,
  CONSTRAINT `fk_Depense_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Depense_Type_depense1`
    FOREIGN KEY (`Type_depense_codeType`)
    REFERENCES `fiscale_db`.`Type_depense` (`codeType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Document_depense`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Document_depense` (
  `idDocument_depense` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `lien` VARCHAR(45) NULL,
  `Depense_idDepense` INT NOT NULL,
  PRIMARY KEY (`idDocument_depense`),
  INDEX `fk_Document_depense_Depense1_idx` (`Depense_idDepense` ASC) VISIBLE,
  CONSTRAINT `fk_Document_depense_Depense1`
    FOREIGN KEY (`Depense_idDepense`)
    REFERENCES `fiscale_db`.`Depense` (`idDepense`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscale_db`.`Personne_a_charge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscale_db`.`Personne_a_charge` (
  `Registre_national_personne_a_charge` INT NOT NULL AUTO_INCREMENT,
  `date_de_naissance` INT(20) NULL,
  `Client_idclient` INT NOT NULL,
  PRIMARY KEY (`Registre_national_personne_a_charge`),
  INDEX `fk_Personne_a_charge_Client1_idx` (`Client_idclient` ASC) VISIBLE,
  CONSTRAINT `fk_Personne_a_charge_Client1`
    FOREIGN KEY (`Client_idclient`)
    REFERENCES `fiscale_db`.`Client` (`idclient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
