# Generated by Django 5.2.8 on 2025-12-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('idadresse', models.AutoField(db_column='idAdresse', primary_key=True, serialize=False)),
                ('rue', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'adresse',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('idville', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code_postal', models.CharField(db_column='code postal', max_length=10)),
            ],
            options={
                'db_table': 'ville',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idclient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(db_column='mot de passe', max_length=50)),
                ('iban', models.CharField(db_column='IBAN', max_length=16)),
                ('adresse', models.ForeignKey(db_column='idadresse', on_delete=django.db.models.deletion.PROTECT, to='client.adresse')),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Independant',
            fields=[
                ('numero_entreprise', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_entreprise', models.CharField(max_length=100)),
                ('date_debut_entreprise', models.CharField(blank=True, max_length=45, null=True)),
                ('client_idclient', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'independant',
            },
        ),
        migrations.CreateModel(
            name='Particulier',
            fields=[
                ('registre_national', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('client', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'db_table': 'particulier',
            },
        ),
        migrations.CreateModel(
            name='PersonneACharge',
            fields=[
                ('registre_national', models.CharField(db_column='registre_national', max_length=11, primary_key=True, serialize=False)),
                ('date_de_naissance', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.PROTECT, to='client.client')),
            ],
            options={
                'db_table': 'personne_a_charge',
            },
        ),
        migrations.AddField(
            model_name='adresse',
            name='ville',
            field=models.ForeignKey(db_column='idville', on_delete=django.db.models.deletion.PROTECT, to='client.ville'),
        ),
    ]
