# Generated by Django 5.2.8 on 2025-12-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particulier',
            name='registre_national',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personneacharge',
            name='registre_national',
            field=models.CharField(db_column='registre_national', max_length=15, primary_key=True, serialize=False),
        ),
    ]
