# Generated by Django 5.2.8 on 2025-12-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_particulier_registre_national_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='independant',
            name='client_idclient',
            field=models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.CASCADE, related_name='independants', to='client.client'),
        ),
        migrations.AlterField(
            model_name='particulier',
            name='client',
            field=models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.CASCADE, related_name='particuliers', to='client.client'),
        ),
    ]
