# Generated by Django 5.2.8 on 2025-12-02 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('idposte', models.AutoField(db_column='idPoste', primary_key=True, serialize=False)),
                ('poste', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'poste',
            },
        ),
        migrations.CreateModel(
            name='MembreCabinet',
            fields=[
                ('idmembre', models.AutoField(db_column='idMembre', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(db_column='mot de passe', max_length=255)),
                ('poste', models.ForeignKey(db_column='idposte', on_delete=django.db.models.deletion.PROTECT, to='comptable.poste')),
            ],
            options={
                'db_table': 'membre_cabinet',
            },
        ),
        migrations.CreateModel(
            name='AttributionDeclarationFiscaleAMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_fiscale', models.ForeignKey(db_column='Declaration_fiscale', on_delete=django.db.models.deletion.CASCADE, to='activite.declarationfiscale')),
                ('membre_cabinet', models.ForeignKey(db_column='Membre_cabinet', on_delete=django.db.models.deletion.CASCADE, to='comptable.membrecabinet')),
            ],
            options={
                'db_table': 'attribution_declaration_fiscale_a_membre',
                'constraints': [models.UniqueConstraint(fields=('membre_cabinet', 'declaration_fiscale'), name='unique_attribution')],
                'unique_together': {('membre_cabinet', 'declaration_fiscale')},
            },
        ),
    ]
