# Generated by Django 5.2.8 on 2025-12-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
        ('comptable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membrecabinet',
            name='declaration_fiscale',
            field=models.ManyToManyField(db_column='Declaration_fiscale', to='activite.declarationfiscale'),
        ),
        migrations.DeleteModel(
            name='AttributionDeclarationFiscaleAMembre',
        ),
    ]
