# Generated by Django 5.2.8 on 2025-12-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activite', '0001_initial'),
        ('comptable', '0002_membrecabinet_declaration_fiscale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membrecabinet',
            name='declaration_fiscale',
        ),
        migrations.CreateModel(
            name='AttributionDeclarationFiscaleAMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_fiscale', models.ForeignKey(db_column='Declaration_fiscale', on_delete=django.db.models.deletion.CASCADE, to='activite.declarationfiscale')),
                ('membre_cabinet', models.ForeignKey(db_column='Membre_cabinet', on_delete=django.db.models.deletion.CASCADE, to='comptable.membrecabinet')),
            ],
            options={
                'db_table': 'attribution_declaration_fiscale_a_membre',
                'constraints': [models.UniqueConstraint(fields=('membre_cabinet', 'declaration_fiscale'), name='unique_attribution')],
                'unique_together': {('membre_cabinet', 'declaration_fiscale')},
            },
        ),
    ]
