# Generated by Django 5.2.8 on 2025-12-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDepense',
            fields=[
                ('codetype', models.IntegerField(db_column='codeType', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'type_depense',
            },
        ),
        migrations.CreateModel(
            name='TypeImpot',
            fields=[
                ('idtype_impot', models.AutoField(db_column='idType_impot', primary_key=True, serialize=False)),
                ('denomination', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'type_impot',
            },
        ),
        migrations.CreateModel(
            name='TypeRevenu',
            fields=[
                ('code_type_revenu', models.IntegerField(db_column='code_Type_revenu', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'type_revenu',
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('iddepense', models.AutoField(db_column='idDepense', primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('annee_depense', models.IntegerField()),
                ('client', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('type_depense', models.ForeignKey(db_column='code_type_depense', on_delete=django.db.models.deletion.PROTECT, to='activite.typedepense')),
            ],
            options={
                'db_table': 'depense',
            },
        ),
        migrations.CreateModel(
            name='DocumentDepense',
            fields=[
                ('iddocument_depense', models.AutoField(db_column='idDocument_depense', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('lien', models.URLField(max_length=255)),
                ('depense', models.ForeignKey(db_column='iddepense', on_delete=django.db.models.deletion.CASCADE, to='activite.depense')),
            ],
            options={
                'db_table': 'document_depense',
            },
        ),
        migrations.CreateModel(
            name='Revenu',
            fields=[
                ('idrevenu', models.AutoField(db_column='idRevenu', primary_key=True, serialize=False)),
                ('montant', models.IntegerField()),
                ('annee_de_perception', models.IntegerField()),
                ('client', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('type_revenu', models.ForeignKey(db_column='code_type_revenu', on_delete=django.db.models.deletion.PROTECT, to='activite.typerevenu')),
            ],
            options={
                'db_table': 'revenu',
            },
        ),
        migrations.CreateModel(
            name='DocumentRevenu',
            fields=[
                ('iddocument_revenu', models.AutoField(db_column='idDocument_revenu', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('lien', models.URLField(max_length=255)),
                ('revenu', models.ForeignKey(db_column='idrevenu', on_delete=django.db.models.deletion.CASCADE, to='activite.revenu')),
            ],
            options={
                'db_table': 'document_revenu',
            },
        ),
        migrations.CreateModel(
            name='DeclarationFiscale',
            fields=[
                ('iddeclaration_fiscale', models.AutoField(db_column='idDeclaration_fiscale', primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
                ('lien', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('soumise', 'Soumise'), ('à_reviser', 'À réviser'), ('valide', 'Validée')], max_length=20)),
                ('client', models.ForeignKey(db_column='idclient', on_delete=django.db.models.deletion.PROTECT, to='client.client')),
                ('type_impot', models.ForeignKey(db_column='idtype_impot', on_delete=django.db.models.deletion.PROTECT, to='activite.typeimpot')),
            ],
            options={
                'db_table': 'declaration_fiscale',
            },
        ),
    ]
